### ISSUE TITLE
error: expected unqualified-id before numeric constant; and error: expected ‘)’ before numeric constant in the 59 line of src/core/memory.h

### ISSUE THREAD

**Issue by ghoshaw** [mmp/pbrt-v3#131]
/usr/PBRT/pbrt-v3/src/core/memory.h:59:9: error: expected unqualified-id before numeric constant
/usr/PBRT/pbrt-v3/src/core/memory.h:59:9: error: expected ‘)’ before numeric constant
/usr/PBRT/pbrt-v3/src/core/pbrtparse.y:894:1: error: expected ‘}’ at end of input
make[2]: *** [CMakeFiles/pbrt.dir/pbrtparse.cpp.o] Error 1
make[1]: *** [CMakeFiles/pbrt.dir/all] Error 2
make: *** [all] Error 2

Does anyone have the same problem?

**Comment by mmp** [comment]
Based on the location of the error, it looks like your compiler may not support the C++11 alignas qualifier. What OS and compiler version are you using?

src/core/port.h has a check that #defines PBRT_HAVE_ALIGNAS for compilers that are known to have it (currently, everything other than MSVC2013); the fix is probably to update that.

**Comment by ghoshaw** [comment]
I use g++ (Debian 4.7.2-5) 4.7.2. and is that a problem?

**Comment by mmp** [comment]
Ok, great. Version 4.7.2 is 4 1/2 years old (https://gcc.gnu.org/gcc-4.7/), and it doesn't really have full support for C++11 (https://gcc.gnu.org/gcc-4.7/cxx0x_status.html). Issue #132 filed to track the broader issue.
