### ISSUE TITLE
SPPM implementation is not symmetric

### ISSUE THREAD

**Issue by TzuChieh** [mmp/pbrt-v3#209]
Hi everyone,

I noticed that PBRT's current implementation of SPPM does not account for the symmetric issue caused by the use of shading normals. According to Veach's paper "Non-symmetric Scattering in Light Transport Algorithms", a weighting factor needs to be used in order to correct this. Is the lack of such weighting factor intentional?

**Comment by wjakob** [comment]
Hi @TzuChieh,

indeed, this issue is neglected in the current implementation. The problem with the weighting factor is that it leads to extremely high variance in the photon weights (with a low probability, you end up dividing by a very small number). Depending on the scene, this can make the method unusable, hence the omission.

Best,
Wenzel

**Comment by TzuChieh** [comment]
@wjakob Thanks for clarifying the problem! I just found out that Mitsuba source code has some relevant comment on this issue, and the weighting factor is not applied too.
