### ISSUE TITLE
obj2pbrt missing WorldBegin / WorldEnd

### ISSUE THREAD

**Issue by sergeyreznik** [mmp/pbrt-v3#211]
It looks like obj2pbrt produces `.pbrt` files  that are not readable by pbrt, because they are missing `WorldBegin` and `WorldEnd` lines.

**Comment by emimvi** [comment]
This seems to be intentional. From the users guide:  

"Note that OBJ files only describe scene geometry; they don’t include camera specifications or descriptions of light sources. (Thus, the generated pbrt input file only includes shape and material specifications that you’ll need to add inside the WorldBegin/WorldEnd block of a full pbrt input file.) Unless you have camera and light source information separately, you’ll need to specify both on your own (see “General Tips” below for some ideas about how to do this.)"
https://www.pbrt.org/users-guide.html#Converting_Scenes_to_pbrts_Format_0

**Comment by mmp** [comment]
Yep, that's intentional, and for that reason.
