### ISSUE TITLE
Sobol Sampler can only sample 1024 dimensions

### ISSUE THREAD

**Issue by alex-rowden** [mmp/pbrt-v3#237]
I am using PBRT to render a large number of files. My scenes are using the Sobol Sampler (ideally for 1024 samples but in debugging a moved to 512 temporarily). When I use a Bidirectional integrator this works perfectly fine but when I use the Direct Lighting integrator it fails on the third file. I will provide the files for reproducibility.

[scenes.zip](https://github.com/mmp/pbrt-v3/files/3129037/scenes.zip)

**Comment by mmp** [comment]
That is, unfortunately, by design; it can be a problem with both the direct lighting integrator, which uses more sampler dimensions than it needs to, as well as with volume rendering. The best thing to do is to just switch to the Halton sampler. Alternatively, you could modify the Sobol sampler to use a random number generator and return random samples once it runs out of dimensions..
