### ISSUE TITLE
Linux rendering exr result is "Decode error" when open it by IrfanView, while the same case on Windows or MacOS is OK. What's wrong?

### ISSUE THREAD

**Issue by hownhoo** [mmp/pbrt-v3#250]
I build the pbrt-v3 on Linux, Windows, MacOS. Every rendering on these OS is normal and can be generate the exr results (for a CG scene by myself). But I encounter an issue that the linux rendering exr result is "Decode error" when trying to open it while the result of same behavior on Windows and MacOS is normal.
What is wrong about the Linux version pbrt rendering result? And how to solve this issue?

Looking forward to get some reply and thanks in advance.

**Comment by mmp** [comment]
Does it open in other image viewers?
Is there anything unusual about the image (very low or very high resolution, etc.)?

You might try building with the latest version of OpenEXR and see if that makes a difference (https://github.com/openexr/openexr).

Otherwise if you can provide a test case we can take a look at it.
