### ISSUE TITLE
Scenes that are provided with PBRT | Conversion to PBRT from other formats

### ISSUE THREAD

**Issue by farhanrw** [mmp/pbrt-v3#253]
Hi everyone. So I am working with pbrt for my project. I am still very new to pbrt and so I was wondering how were the scenes that come with PBRT converted to a .pbrt format? The scenes I am talking about are these. _https://pbrt.org/scenes-v3.html_ I know there are a few guys who built plugins that work with Maya or Blender but as far as i have seen those did not feel like to be very stable (Sorry if I am wrong). 

So I was wondering is there any other way these scenes were made in say blender/maya and then converted to PBRT format? If so how are the materials being mapped while converting from a format to the other.

A point to note here is that in my project I want to buy a urban 3D model that comes with PBR representation for the materials (not just flat textures). Then I plan to convert this to pbrt format and render from different camera position. Is this too far fetched? Or can this be easily done? (I know how to change camera and other things, I am talking about the conversion and material mapping thing).

I apologize again if my questions are too naive and ill-placed. However any sort of help from a few of you or some guidelines would help me a lot to progress further.

Regards,
Farhan

**Comment by mmp** [comment]
Most of those were converted from Blender using Blender's obj export and then the obj2pbrt tool that comes with pbrt. (And then with a bunch of manual editing to set camera positions and tweak materials.)

The measure-one, transparent-machines, and landscape scene were all exported using the Cinema4D exporter that comes with pbrt. (It didn't get all of the materials, though, so that also required manual tweaking.)

It would be nice to have a USD or FBX converter, or something based on Assimp. Contributions welcome :-)
