### ISSUE TITLE
Question about AbsDot in the rendering

### ISSUE THREAD

**Issue by deadmarston** [mmp/pbrt-v3#278]
Hi there,

In the rendering part, you use `beta *= f * AbsDot(wi, isect.shading.n) / pdf;` , I wonder why you don't use Dot since that seems to be correct value for cosTheta.

Thanks

**Comment by mmp** [comment]
The normal and wi may be on different sides of the surface, in which case `Dot` would give a negative value. (pbrt doesn't flip the normal to match `wi`'s side, so that the normal orientation can still be used to determine if a ray is entering or exiting a surface, under the assumption that the normal points outside..)

**Comment by deadmarston** [comment]
Thanks:)
