### ISSUE TITLE
Why Oren-Nayar has only reflection, no transmission?

### ISSUE THREAD

**Issue by bhouston** [mmp/pbrt-v3#28]
I was wondering why the current implementation of Oren-Nayar microfacet model of diffuse reflection does not allow for a similar Oren Nayar transmission BxDF?  I think theoretically it should be possible to have Oren-Nayer transmission?

There is a LambertianReflection and a LambertianTransmission BxDFs, but the OrenNayer BxDF appears to only be Reflection.

I mention this in part because the Oren-Nayar "sigma" parameter for adjusting diffuse roughness is only used by the Matte material and not on the Translucent material, even though both attempt to model a diffuse component.

**Comment by bhouston** [comment]
I guess some people only use the roughness parameter when calculating reflections and ignore it for transmission -- thus OrenNayarReflection would be then paired with a LambertianTransmission BxDF?

**Comment by wjakob** [comment]
Hi Ben,

that's a good observation. There is no reason why you couldn't have a microfacet BTDF with diffusely transmissive facets. Since the scattering function of diffuse facets are not Dirac deltas, you'd have to compute (or approximate) an integral as in the case of the Oren-Nayar model for reflection. There is always a space tradeoff in the book (anything we add somewhere needs to be removed elsewhere) -- but it might make sense to add it as an advanced exercise in PBRTv4.

Best,
Wenzel
