### ISSUE TITLE
Invalid case for SampledSpectrum 

### ISSUE THREAD

**Issue by marwan-abdellah** [mmp/pbrt-v3#55]
The **SampledSpectrum** class uses the function `AverageSpectrumSamples` to average the loaded spectra from .spd files. This function gives a wrong spectrum in case of monochromatic SPDs that are sampled with 1 nm resolution. For example a laser beam that is delta Dirac, or has only certain intensity at one wavelength. This function splits the value between two wavelengths, which is completely wrong and can significantly change the results of the rendering.   

To reproduce the error, just set 
`static const int sampledLambdaStart = 400;`
`static const int sampledLambdaEnd = 700;`
`static const int nSpectralSamples = 300;`

and load the .spd file that has a monochromatic spectrum (1000 at 650 nm, given below) 
If you print the values of the resulting spectrum, you will get the following result
`...`
`at[649] = 0`
`at[650] = 500`
`at[651] = 500`
`at[652] = 0`
`...`

However, you should get the following 
`...`
`at[649] = 0`
`at[650] = 500`
`at[651] = 0`
`at[652] = 0`
`...`

Proposed solution:
Add one more argument to the `AverageSpectrumSamples` that reflect the index of the wavelength, and then check if the spectrum has sampling of 1 nm or not. If yes, then return the power at the given index, otherwise, average the spectrum. 

`Float AverageSpectrumSamples(const Float *lambda, const Float *vals,
                                    int n, Float lambdaStart, Float lambdaEnd,
                                    const int index)`

`if ((sampledLambdaEnd - sampledLambdaStart) == nSpectralSamples) return vals[index];`

[ **laser.spd** ]
400 0
401 0
402 0
403 0
404 0
405 0
406 0
407 0
408 0
409 0
410 0
411 0
412 0
413 0
414 0
415 0
416 0
417 0
418 0
419 0
420 0
421 0
422 0
423 0
424 0
425 0
426 0
427 0
428 0
429 0
430 0
431 0
432 0
433 0
434 0
435 0
436 0
437 0
438 0
439 0
440 0
441 0
442 0
443 0
444 0
445 0
446 0
447 0
448 0
449 0
450 0
451 0
452 0
453 0
454 0
455 0
456 0
457 0
458 0
459 0
460 0
461 0
462 0
463 0
464 0
465 0
466 0
467 0
468 0
469 0
470 0
471 0
472 0
473 0
474 0
475 0
476 0
477 0
478 0
479 0
480 0
481 0
482 0
483 0
484 0
485 0
486 0
487 0
488 0
489 0
490 0
491 0
492 0
493 0
494 0
495 0
496 0
497 0
498 0
499 0
500 0
501 0
502 0
503 0
504 0
505 0
506 0
507 0
508 0
509 0
510 0
511 0
512 0
513 0
514 0
515 0
516 0
517 0
518 0
519 0
520 0
521 0
522 0
523 0
524 0
525 0
526 0
527 0
528 0
529 0
530 0
531 0
532 0
533 0
534 0
535 0
536 0
537 0
538 0
539 0
540 0
541 0
542 0
543 0
544 0
545 0
546 0
547 0
548 0
549 0
550 0
551 0
552 0
553 0
554 0
555 0
556 0
557 0
558 0
559 0
560 0
561 0
562 0
563 0
564 0
565 0
566 0
567 0
568 0
569 0
570 0
571 0
572 0
573 0
574 0
575 0
576 0
577 0
578 0
579 0
580 0
581 0
582 0
583 0
584 0
585 0
586 0
587 0
588 0
589 0
590 0
591 0
592 0
593 0
594 0
595 0
596 0
597 0
598 0
599 0
600 0
601 0
602 0
603 0
604 0
605 0
606 0
607 0
608 0
609 0
610 0
611 0
612 0
613 0
614 0
615 0
616 0
617 0
618 0
619 0
620 0
621 0
622 0
623 0
624 0
625 0
626 0
627 0
628 0
629 0
630 0
631 0
632 0
633 0
634 0
635 0
636 0
637 0
638 0
639 0
640 0
641 0
642 0
643 0
644 0
645 0
646 0
647 0
648 0
649 0
650 1000
651 0
652 0
653 0
654 0
655 0
656 0
657 0
658 0
659 0
660 0
661 0
662 0
663 0
664 0
665 0
666 0
667 0
668 0
669 0
670 0
671 0
672 0
673 0
674 0
675 0
676 0
677 0
678 0
679 0
680 0
681 0
682 0
683 0
684 0
685 0
686 0
687 0
688 0
689 0
690 0
691 0
692 0
693 0
694 0
695 0
696 0
697 0
698 0
699 0
700 0

**Comment by mmp** [comment]
Sorry for the very slow response on this. I've spent a bit of time on this over the past few days, and have come to the conclusion that a) this is working as intended, though b) 'intended' is probably not the best approach. There's a workaround in the following, but revamping the system to use a better approach would be fairly disruptive at this point, so will probably have to wait for pbrt-v4.

The representation used by SampledSpectrum (as discussed in the book) is that the SPD is modeled as being piecewise constant, where each sample represents a range of wavelengths. So, if sampledLambdaStart=400, sampledLambdaEnd=700, and nSpectralSamples=3, then the first sample represents 400-500nm, the second 500-600nm, and the third 600-700nm. However, the model for specifying a SPD in the scene description is that the SPD is a piecewise-linear function, interpolated between a given set of (wavelength, value) pairs. In turn, we compute the average of that function over the range of wavelengths corresponding to each spectral sample when the scene description is parsed.

(Thus, for your input, the piecewise linear function goes from 0 and 649nm to 1000 at 650nm and then to 0 at 651nm. When it's converted to the piecewise-constant representation, we have a bucket from 649nm-650nm, which gets the average value of the piecewise-linear function over that range, 500, and similarly for 650nm-651nm.)

Now, this is fairly annoying / unintuitive. As a workaround, you might try specifying your input like:

...
650 0
650.1 10000
650.2 0
..

That spike from 0-10000 over a range of .2 should turn into a value of 1000 for the piecewise-constant SPD from 650-651nm. (This is admittedly a gross hack, though is somewhat in the spirit of a delta distribution at that wavelength. Sort of.)

I don't see a clean way to fix this. One might want to update the scene specification conventions so that instead of describing a piecewise-linear function, one describes a piecewise-constant function, but in this case, we either need one fewer SPD value than currently (if we're only specifying the function value between given wavelengths), or one more (if we're specifying the function value before the first wavelength and after the last one.)

Now, what we should have done is just specified that the sample values in SampledSpectrum are just point samples at single wavelengths. However, there's a lot of code that currently assumes the piecewise-constant representation (all of the averaging of XYZ basis functions over wavelength ranges and the like), such that I don't think changing this now makes sense, since the code would be fairly far diverged from what is documented in the book.  Therefore, this will have to wait for pbrt-v4...

Many thanks for noting this issue!
