### ISSUE TITLE
use of const

### ISSUE THREAD

**Issue by z-boson** [mmp/pbrt-v3#96]
Hello,

I have a suggestion about the readability of the code: The code would be better readable/maintainable if `const` is used wherever possible, f.e. for local variables that are never changed.

Thank you for your effort!
Greetings, z-boson

**Comment by mmp** [comment]
It's a good suggestion. However, one slightly unusual constraint with pbrt is the fact that the code is printed in the book. Given the length of the book, we make a number of choices in how the code is written in order to save space--for example, using `const` in those cases would cause some lines of code to require two lines of text rather than one, which would end up adding a few pages to the overall book length, which in turn might mean that we'd have to have less text on a given topic (or wouldn't be able to discuss it at all.)
